### PR TITLE
polish plots and add function of lepton over hadron

### PR DESCRIPTION
**Pull request by zhangbiao-phy**

### CODE REVIEW

**Comment by ginnocen** [comment]
@zhangbiao-phy is this still valid? should i merge it?

**Comment by zhangbiao-phy** [comment]
> @zhangbiao-phy is this still valid? should i merge it?

yes, It still valid, It's fine for me if you can merge it. otherwise, I will take a backup for this script in local

**Comment by vkucera** [comment]
@zhangbiao-phy @ginnocen Can you please check whether this version still works with the latest O2Physics and whether it should be merged as it is?

**Comment by zhangbiao-phy** [comment]
> @zhangbiao-phy @ginnocen Can you please check whether this version still works with the latest O2Physics and whether it should be merged as it is?

Hi @vkucera, It works for this task: https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/Tasks/qaPidRejection.cxx
I think you can merge it.

**Comment by vkucera** [comment]
I noticed that this PR was merged into the run5 branch. If you want to propagate the changes to master, please make a new PR.

**Pull request merged**
