### PR TITLE
Add Dplus comparison plots

### PR DESCRIPTION
**Pull request by fcatalan92**
Needs ~https://github.com/alisw/AliPhysics/pull/16108~ (merged), ~https://github.com/alisw/AliPhysics/pull/16118~ (merged) and ~https://github.com/AliceO2Group/AliceO2/pull/4797~ (merged)

### CODE REVIEW

**Comment by ginnocen** [comment]
@vkucera @fcatalan92 is this good to go?

**Comment by fcatalan92** [comment]
> @vkucera @fcatalan92 is this good to go?

Not yet

**Comment by ginnocen** [comment]
OK.

**Review by vkucera — CHANGES_REQUESTED** [review]
This PR is not compatible with the latest AliPhysics and O2. Is there an update planned?

**Comment by fcatalan92** [comment]
> This PR is not compatible with the latest AliPhysics and O2. Is there an update planned?

Hi @vkucera, yes I planned to update it but I didn't manage yet. I will do in the next days

**Comment by vkucera** [comment]
> > This PR is not compatible with the latest AliPhysics and O2. Is there an update planned?
> 
> Hi @vkucera, yes I planned to update it but I didn't manage yet. I will do in the next days

OK, converting to a draft until then.

**Comment by fcatalan92** [comment]
@vkucera I updated the PR and now the code runs fine. However, the comparison plots are in strong disagreement 
[comparison_histos_2prong.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5765134/comparison_histos_2prong.pdf), [comparison_histos_3prong.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5765135/comparison_histos_3prong.pdf). It looks to me that the discrepancy could be at the track selection level since for the Dplus no candidate selections are applied (both in O2 and in AliPhysics). Is the vertexer the same?

P.s. I'm running with updated AliPhysics and O2 (today's master)

**Review by vkucera — CHANGES_REQUESTED** [review]
Please rebase from the master, fix conflicts and force push to enable the linter checks.

**Comment by ginnocen** [comment]
hi @fcatalan92, could you rebase and resolve the conflicts so that we can merge this PR?

**Comment by fcatalan92** [comment]
> hi @fcatalan92, could you rebase and resolve the conflicts so that we can merge this PR?

Done.

I have also opened a PR in O2 https://github.com/AliceO2Group/AliceO2/pull/5204 adding the use of pre-selections for the Dplus. Now the comparison plots are in better agreement [comparison_histos_dplus.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5825935/comparison_histos_dplus.pdf) with respect to the old version [comparison_histos_dplus_noPreSel_beforePR.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5825937/comparison_histos_dplus_noPreSel_beforePR.pdf) even if some discrepancies are still present. The default configuration returns quite different results for Lc [comparison_histos_lc.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5825941/comparison_histos_lc.pdf) and D0 [comparison_histos_d0.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5825942/comparison_histos_d0.pdf) between AliPhysics and O2.

An additional minor things, running the `runtest.sh` script I get warnings and errors [terminal_out.txt](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5825947/terminal_out.txt) even if everything works fine and I get the comparison plots. The logs file do not show anything strange

**Comment by ginnocen** [comment]
hi @fcatalan92, thanks. "The default configuration returns quite different results for Lc comparison_histos_lc.pdf and D0 comparison_histos_d0.pdf between AliPhysics and O2" -> yes this is correct. But It is overall the same issue. It is the contamination of candidates from other decay channels (in the Lc, you see e.g. the Ds and in the D0 you see the Jpsi channel), which is big if you don't apply selections.

**Comment by ginnocen** [comment]
hi @fcatalan92 could you try to set dcatoprimxymin_3prong to 0 in your JSON config (if not done already?).
There is a known difference in the dca single track selection between run2 and run3.

**Comment by vkucera** [comment]
Hi @fcatalan92 

> The log files do not show anything strange.

What is in the comparison log file?

**Comment by fcatalan92** [comment]
> What is in the comparison log file?

There is an error related to a histogram binning ([log_postprocess.log](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5828899/log_postprocess.log)) indeed. However, it seems to me that spurious warnings and errors, that do not affect the workflow, are caught.

@ginnocen Setting `dcatoprimxymin_3prong` to 0, I get a result compatible with yours [comparison_histos_dplus.pdf](https://github.com/AliceO2Group/Run3Analysisvalidation/files/5828973/comparison_histos_dplus.pdf). 

In my opinion, this PR is ready to be merged.

**Comment by ginnocen** [comment]
hi @fcatalan92 thanks for checking, it seems all consistent. Vit is looking into those warnings that seem indeed to be not very informative. I will merge this one.

**Comment by vkucera** [comment]
@fcatalan92 I see. The binning mismatch is coming from the skimming, not your task, so that is fine.

Please remove the reference plots from your PR. They are obsolete now and will should be replaced with the per-task plots once we reach a decent AliPhysics/O2 agreement.

**Comment by ginnocen** [comment]
@fcatalan92 why are you updating the reference plots?

**Comment by fcatalan92** [comment]
> Please remove the reference plots from your PR. They are obsolete now and should be replaced with the per-task plots once we reach a decent AliPhysics/O2 agreement.

Done, they were a remnant of the first version of the PR

**Comment by vkucera** [comment]
Thanks, looks good to me.
Just a minor fix. Can you please fix these? `cm^2` -> `cm^{2}`

**Comment by fcatalan92** [comment]
> Thanks, looks good to me.
> Just a minor fix. Can you please fix these? `cm^2` -> `cm^{2}`

Done.

**Comment by vkucera** [comment]
Thanks a lot for the quick fix!

**Comment by ginnocen** [comment]
hi @vkucera just wait for #5204 O2 to be merged.

**Review by vkucera — APPROVED** [review]

**Pull request merged**
