### PR TITLE
Update jpsi with JSON for 2D cuts and 2D histograms.

### PR DESCRIPTION
**Pull request by zhangbiao-phy**
synchronize the O2 jpsi task: https://github.com/AliceO2Group/AliceO2/pull/5768

### CODE REVIEW

**Comment by vkucera** [comment]
Please fix the bugs and link the O2 PR.

**Comment by zhangbiao-phy** [comment]
> Please fix the bugs and link the O2 PR.

it's Ok now

**Comment by vkucera** [comment]
> > Please fix the bugs and link the O2 PR.
> 
> it's Ok now

Please add the missing link to the O2 PR.

**Comment by zhangbiao-phy** [comment]
synchronize the O2 jpsi task: https://github.com/AliceO2Group/AliceO2/pull/5768

**Comment by zhangbiao-phy** [comment]
> > > Please fix the bugs and link the O2 PR.
> > 
> > 
> > it's Ok now
> 
> Please add the missing link to the O2 PR.

done

**Review by vkucera — APPROVED** [review]
Cut arrays tested by @zhangbiao-phy with the fixed version.

**Pull request merged**
