### PR TITLE
Add X task.

### PR DESCRIPTION
**Pull request by rspijkers**
This simply adds the X task to the config_task.sh

Edit: The corresponding PR in O2: AliceO2Group/AliceO2#5469

### CODE REVIEW

**Review by ginnocen — COMMENTED** [review]
hi @vkucera can you also have a look?

**Comment by vkucera** [comment]
Run 3 configuration is missing.

**Comment by ginnocen** [comment]
hi @rspijkers, could you address the last comment from @vkucera ?

**Comment by rspijkers** [comment]
> hi @rspijkers, could you address the last comment from @vkucera ?

I think I already did by adding it to the json, is more work required?

**Pull request merged**
