### PR TITLE
HF adding preselection configurables

### PR DESCRIPTION
**Pull request by nzardosh**
Please do not merge until O2 pull 4873 has been merged

### CODE REVIEW

**Comment by vkucera** [comment]
**To be merged after https://github.com/AliceO2Group/AliceO2/pull/4873**

**Comment by vkucera** [comment]
Tabs! :'‑(

**Comment by ginnocen** [comment]
@vkucera @nzardosh we wait until we have the aliphysics modifications and O2 in right?

**Comment by vkucera** [comment]
> @vkucera @nzardosh we wait until we have the aliphysics modifications and O2 in right?

Yes

**Pull request merged**
